### ISSUE TITLE
Rename integration tests lib.rs

### ISSUE THREAD

**Issue by Michael-F-Bryan** [geaz/bittrex-api#1]
Each `*.rs` file in your `tests/` directory will be compiled and tested individually, so I don't think it makes sense to name your integration test `tests/lib.rs`. It's not really a library after all. 

In [mdbook] we've named the integration test files after the general area they are exercising. Perhaps a similar pattern would work for you?

[mdbook]: https://github.com/azerupi/mdBook/tree/master/tests

**Comment by geaz** [comment]
Good advise. I renamed `tests/lib.rs` to `tests/client.rs`. Now it is obvious that the test file is testing.
