### ISSUE TITLE
Top level docs and re-exports

### ISSUE THREAD

**Issue by Michael-F-Bryan** [geaz/bittrex-api#3]
Usually if you have a nested library you'll re-export the most important types at the top level to make life easier. 

In this case the `api` module only contains a single thing so you may want "inline" the `api` module and just export the `BittrexAPI` directly.

i.e. Make your `lib.rs` look something like this:

```rust
...
pub mod error;
pub mod values;
mod api;

pub use api::BittrexAPI;
```

---

Also, if you were to describe the `BittrexAPI`, would you say it's an `API` or a `Client`? I was thinking you'd call it a `BittrexClient` seeing as it's a client which is interacting with the Bittrex API and the `*Client` is a fairly common naming scheme.

**Comment by geaz** [comment]
Thank you very much for the re-export hint! This was exactly what I was missing here. And you are totally right. The `BittrexAPI` should definitely be `BittrexClient`.
