### ISSUE TITLE
get_balance Error

### ISSUE THREAD

**Issue by inv2004** [geaz/bittrex-api#5]
Hello. Thank you for the library.

Looks like bittrex_client.get_balances() does not work for me :
```
called `Result::unwrap()` on an `Err` value: BittrexError { error_type: APIError, message: "Problem parsing information missing field `Requested` at line 1 column 175" }
```

**Comment by geaz** [comment]
Hello,
this library was more a programming challenge for me and I don't use it at the moment. As far as I know, Bittrex did a change on their API. Changes on the library could be necessary.
 
P.S.: Sorry for the late answer

**Comment by inv2004** [comment]
No problem. anyway, library works perfect, except mentioned problem.

**Comment by monomadic** [comment]
Submitted a PR for this at https://github.com/geaz/bittrex-api/pull/6 - works now.

**Comment by geaz** [comment]
Thank you for the fix! I merged the request 👍
